// src/constants/matrices/trdm.matrix.ts

export const TRDM_SECCIONES_EXCEL = {
  // 1. OBJETOS ASEGURADOS Y LÍMITES A VALOR TOTAL
  LIMITES_A_VALOR_TOTAL: [
    "Edificio, instalaciones y adecuaciones fijas y permanentes",
    "Maquinaria y equipos e instalaciones",
    "Mercaderías y/o inventarios incluyendo materia prima, producto en proceso y producto terminado",
    "Muebles, enseres, equipos de oficina, adecuaciones e instalaciones",
    "Obras de arte",
    "Joyas",
    "Herramientas",
    "Equipo electrónico fijo",
    "Equipo electrónico portatil",
    "Equipos tipo celulares, tablets y equipos de comunicación",
    "Drones",
    "Equipo médico",
    "Dinero y/o valores en permanenecia",
    "Dinero y/o Valores en Tránsito: Estimado anual de movilización",
    "Dinero y/o Valores en Tránsito: Limite por embarque",
    "Lucro Cesante por Incendio (Utilidad Bruta / Margen de contribución) - Periodo de indemnización 12 meses",
    "Lucro Cesante por Rotura (Utilidad Bruta / Margen de contribución) - Periodo de indemnización 12 meses"
  ],

  // 2. LÍMITES ASEGURADOS A PRIMER RIESGO ABSOLUTO Y POR EVENTO
  LIMITES_A_PRIMER_RIESGO: [
    "Robo y/o Asalto y/o Atraco",
    "Bienes de socios incluyendo equipos electronicos, celulares y prendas de vestir",
    "Hurto y/o desaparición misteriosa, incluye partes y piezas de la mercaderia y bienes de socios",
    "Robo durante saqueo",
    "Equipo Electrónico: Hurto y/o desaparición misteriosa, incluye partes y piezas del equipo electrónico, incluyendo portátiles dentro de predios",
    "Equipo Electrónico: Robo y/o asalto con fractura, dentro de vehículo en cajuela",
    "Sección II: Portadores externos de datos y la información contenida en ellos",
    "Sección III: Incremento en costos de operación (En días)"
  ],

  // 3. COBERTURAS (Hechos súbitos e imprevistos)
  COBERTURAS_PRINCIPALES: [
    "Incendio y/o rayo",
    "Explosión",
    "Implosión, incluyendo la explosión proveniente de actos malintencionados de terceros",
    "Actos mal intencionados del personal del asegurado",
    "Daños a las instalaciones durante saqueo",
    "Alúd, deslaves, caída de rocas, agrietamiento",
    "Crecientes y deslizamientos de tierra producidos por agua",
    "Terremoto",
    "Maremoto, tsunami",
    "Temblor",
    "Erupción volcánica",
    "Lluvia e inundación incluye granizada",
    "Daños por agua",
    "Motin, huelga",
    "Asonada",
    "Invasiones",
    "Conmoción civil",
    "Disturbios laborales",
    "Alborotos populares",
    "Actos mal intencionados de terceros",
    "Daño malicioso",
    "Colapso",
    "Cobertura extendida amplia",
    "Rotura de vidrios, cristales, domos, letreros, vallas, membretes, grabados o epigramas",
    "Asentamiento de muros, pisos, techos, pavimentos o cimientos",
    "Equipo electrónico: Suspensión de energía eléctrica proveniente de la red pública",
    "Equipo electrónico: Daños por variaciones de voltaje",
    "Equipo electrónico: Hurto de equipos electrónicos fijos",
    "Equipo electrónico: Hurto de equipo electrónico portátil",
    "Robo y/o asalto con violencia y amenaza",
    "Escalamiento",
    "Hurto",
    "Saqueo",
    "Dinero y/o valores en permanencía y/o transito",
    "Rotura de Maquinaria: Autoexplosión",
    "Rotura de Maquinaria: Implosión",
    "Rotura de Maquinaria: Impericia",
    "Rotura de Maquinaria: Negligencia",
    "Rotura de Maquinaria: Errores de diseño",
    "Rotura de Maquinaria: Defectos de instalación y/o construcción y/o montaje",
    "Rotura de Maquinaria: Fundición",
    "Rotura de Maquinaria: Materiales defectuosos",
    "Rotura de Maquinaria: Defectos de mano de obra",
    "Rotura de Maquinaria: Daños por sobre carga",
    "Rotura de Maquinaria: Cimentaciones y pisos"
  ],

  // 4. AMPAROS ADICIONALES (A primer riesgo absoluto y por evento)
  AMPAROS_ADICIONALES: [
    "Arrendamiento de bodegas o locales sustitutos",
    "Arrendamientos (12 meses) (Pérdida de ingresos por renta)",
    "Autoexplosión",
    "Bienes en exposición o demostración",
    "Cláusula eléctrica amplia",
    "Combustión espontánea amplia",
    "Contratistas y subcontratistas independientes",
    "Documentos y modelos",
    "Flete aéreo y/o expreso",
    "Gastos adicionales por horas extras, trabajo nocturno y días feriados",
    "Gastos de incineración del salvamento",
    "Gastos de viaje y estadía",
    "Gastos extraordinarios y suplementarios",
    "Gastos financieros por bloqueo de fondos",
    "Gastos para extinguir un incendio",
    "Gastos para la preservación de bienes",
    "Gastos para recuperación de cheques",
    "Honorarios de auditores, revisores y contralores",
    "Honorarios de profesionales",
    "Intereses por bloqueo de fondos",
    "Portabilidad territorial",
    "Portabilidad extraterritorial, incluye negligencia, hurto, robo y daños o pérdidas por cualquier causa, mientras los bienes citados se hallen instalados o transportados",
    "Propiedad personal de ejecutivos y empleados",
    "Proveedores, distribuidores nacionales e internacionales",
    "Refrigeración y/o congelación amplia",
    "Remoción de escombros incluyendo demolición o incremento del costo de construcción",
    "Rotura de tanques y pérdida de contenidos",
    "Rotura de tuberías",
    "Rotura de vidrios, cristales, domos, letreros, vallas, membretes, grabados o epigramas",
    "Terrorismo y Sabotaje"
  ],

  // 5. CLÁUSULAS ADICIONALES (Desglosadas 1:1)
  CLAUSULAS_ADICIONALES: [
    "Aceites, lubricantes o refrigerantes, combustibles y explosivos siempre que sean consecuencia de un siniestro",
    "Ajuste de primas en lucro cesante",
    "Adhesión",
    "Designación de ajustadores y peritos de mutuo acuerdo",
    "Alteraciones y reparaciones",
    "Amparo automático de nuevas propiedades y/o bienes, 30 días",
    "Amparo automático de nuevas predios, 30 días",
    "Amparo automático de nuevos equipos, 30 dias",
    "Amparo de bienes propios y/o de terceros",
    "Ampliación de aviso de siniestro, 10 días hábiles",
    "Anticipo de siniestros hasta un 50% en un plazo de 8 días",
    "Arbitraje",
    "Autoridad Civil",
    "Automaticidad",
    "Avisos y letreros",
    "Bienes en consignación y depósito",
    "Bienes a la intemperie",
    "Bienes en exposición y/o demostración",
    "Bienes en propiedad de terceros",
    "Bienes de terceros bajo responsabilidad del asegurado",
    "Caída accidental de la carga",
    "Cancelación de la póliza 30 dias",
    "Cancelación a prorrata",
    "Cadenas y cintas transportadoras",
    "Cláusula de combustibles y explosivos",
    "Cláusula de derrame accidental de productos",
    "Cláusula de hornos",
    "Cláusula de protección de marca",
    "Cobertura para el componente electrónico de maquinaria y el componente mecánico del equipo electrónico",
    "Contabilidad y prueba",
    "Cimentaciones (Rotura de Maquinaria)",
    "Deducible por local o dirección asegurada y/o rubro afectado",
    "Derrame de tanques y/o pérdida de contenidos",
    "Designación de bienes",
    "Destrucción preventiva",
    "Extintores",
    "Exclusión distorsión/corrupción de información (Cyber)",
    "Elección de reparación",
    "Eliminación articulo correspondiente a la regla proporcional para amparos adicionales",
    "Errores u omisiones no intencionales de descrpción solamente",
    "Extensión de vigencia a prorrata, 30 días",
    "Gastos para demostración de pérdidas",
    "Gastos para aminorar la pérdida 100%",
    "Gastos de limpieza de ceniza/humo",
    "Gastos para ajuste de pérdida a cargo de la aseguradora",
    "Flotante 70% de prima en depósito y ajuste a final de vigencia",
    "Impedimiento de acceso (LC)",
    "Indemnización para lavandería",
    "Intereses de contratistas",
    "Interés asegurable diverso",
    "La inspección del siniestro se realizará dentro de las 48 horas",
    "Libre tránsito entre locales incluyendo mercaderia",
    "Localización y libre tránsito",
    "Manipuleo de productos",
    "Maquinaria y equipo bajo tierra",
    "Materiales en fusión",
    "Materiales importados",
    "Materiales refractarios en hornos, calderas y similares",
    "Mercadería en propiedades de terceros",
    "Moldes y matrices",
    "No cancelación individual de la póliza o cobertura",
    "Obras civiles",
    "Otras propiedades",
    "Pago de siniestros en 8 días desde la entrega del último documento",
    "Pago de primas 30 dias plazo",
    "Par y juego",
    "Inspección y reparación",
    "Primera opción de compra",
    "Propiedades fuera del control del asegurado",
    "Propiedad horizontal",
    "Protección de marca",
    "Refrigeración y/o congelación (24 horas)",
    "Reparaciones y alteraciones en lucro cesante",
    "Reparaciones inmediatas, previa autorización",
    "Remoción de materiales en fusión",
    "Reposición o reemplazo",
    "Restitución automática de suma asegurada sin costo",
    "Riesgos en paralización",
    "Robo o tentativa de robo a consecuencia de siniestro",
    "Salvamento",
    "Salvataje",
    "Seguro insuficiente parcial hasta el 20%",
    "Sellos y marcas",
    "Suspensión de energía eléctrica, agua, o gas (Lucro Cesante)",
    "Fallo o interrupción de energía eléctrica, agua, o gas (Rotura de Mauinaria, Equipo Electrónico y Lucro Cesante)",
    "Tolerancia 10%",
    "Traslado temporal"
  ],

  // 6. NOTAS ACLARATORIAS Y CONDICIONES ESPECÍFICAS
  NOTAS_ACLARATORIAS: [
    "Cobertura a albercas, patios exteriores, escaleras exteriores",
    "Cobertura a cimientos y muros de contención debajo del nivel del piso",
    "Cobertura a frescos, murales o adornos artísticos",
    "Cobertura a antenas exteriores de radio y/o televisión, redes de luz y teléfono",
    "Cobertura a canales de regadío, de agua de lluvia, desagües, cañerías",
    "Cobertura a piletas, piscinas, cercas, muros exteriores, embarcaderos, muelles",
    "En lucro cesante, gastos extraordinarios se cubrirán hasta la suma asegurada total",
    "En lucro cesante, el deducible en días será aplicable sobre la pérdida real sufrida",
    "Revisar lucro cesante contingente",
    "Mantenimiento de Equipo Electrónico por personal del asegurado y/o terceros",
    "En Equipo Electrónico, indemnización incluye fletes ordinarios, montaje y derechos aduaneros",
    "Para Incremento en costo de operación, deducible porcentual o fijo (No en días)",
    "Daños por variación de voltaje en UPS",
    "Tabla de Depreciación Equipo Electrónico: 0 a 2 años 0%, 3er año 10%, 4to año 20%, 5to año 40%, 6to año 50%",
    "Pólizas de Rotura de Maquinaria y Equipo Electrónico tipo blanket",
    "Tabla de Depreciación Rotura de Maquinaria: 0 a 3 años 0%, 3 a 10 años 5%, Más de 10 años 8% (máximo 50%)",
    "Mantenimiento de maquinaria por personal del asegurado y/o terceros",
    "Daños causados por sobrecarga o esfuerzo excesivo en Rotura de Maquinaria",
    "Cobertura RM incluye bandas, correas, cadenas, cables, matrices, llantas, filtros, tamices",
    "Robo cubre violencia, intimidación, escalamiento, ganzúas y apropiación de llaves",
    "Movilización de dinero en vehículos propios y/o de terceros al 100%",
    "Movilización de dinero en taxis, motos, a pie, App (Uber) o transporte público",
    "Movilización de dinero a pie desde el vehículo hasta el predio cubierta al 100%",
    "Inventario declarado es: diario y/o promedio mensual y/o valor final de mes",
    "No se aplicará deducible en amparos adicionales",
    "Eximir presentación del informe final de investigaciones",
    "Cobertura para maquinaria y equipo bajo tierra, bombas sumergibles (Florícolas/agrícolas)",
    "Valores asegurados corresponden a valores de reposición a nuevo",
    "Cobertura extendida cubre impacto de aeronaves dentro del cono de aproximación",
    "Cobertura extendida cubre daños por viento sin exigencia de velocidad mínima",
    "Cobertura extendida cubre impacto de vehículos y montacargas propios y no propios",
    "Daños por humo proveniente de defecto de maquinaria",
    "Cobertura en direcciones eventuales (bodegaje, empaquetamiento, maquila)",
    "Impacto de aeronaves cubre daños a bienes propios y de terceros",
    "Impacto de vehículos propios incluye caída de árboles",
    "Se cubre dinero de ejecutivos y personal del asegurado",
    "Robo de cheques ampara el valor nominal si son cobrados o irrecuperables",
    "Se cubre daños causados por animales, insectos y roedores",
    "Se incluye incendio cuyo origen sea forestal",
    "Cláusulas adicionales aplican a todas las pólizas si se emiten ramos separados"
  ]
} as const;

export const TRDM_MATRIZ_COMPLETA = [
  ...TRDM_SECCIONES_EXCEL.LIMITES_A_VALOR_TOTAL,
  ...TRDM_SECCIONES_EXCEL.LIMITES_A_PRIMER_RIESGO,
  ...TRDM_SECCIONES_EXCEL.COBERTURAS_PRINCIPALES,
  ...TRDM_SECCIONES_EXCEL.AMPAROS_ADICIONALES,
  ...TRDM_SECCIONES_EXCEL.CLAUSULAS_ADICIONALES,
  ...TRDM_SECCIONES_EXCEL.NOTAS_ACLARATORIAS
] as const;